### ISSUE TITLE
How to disable show autocomplete when enter space?

### ISSUE THREAD

**Issue by pelemarse** [sublimelsp/LSP-vue#100]
Sublime Text 3.2.2, Build 3211
LSP-vue 1.1.5

https://user-images.githubusercontent.com/29234307/114116607-a7834080-98ed-11eb-871e-89edc280ae28.mov

**Comment by rchl** [comment]
The server decides that it wants the completions to be triggered on space.

I don't think you can change that in ST3 but it should be doable in ST4 (in a way).

**Comment by pelemarse** [comment]
> The server decides that it wants the completions to be triggered on space.
> 
> I don't think you can change that in ST3 but it should be doable in ST4 (in a way).

I now testing ST4. This feature will appear in the LSP-vue package or in the Sublime Text editor settings itself?

**Comment by rchl** [comment]
In ST4 you can do this:
- open `Preferences: LSP-vue Settings` from the command palette
- on the right side insert:
```
"auto_complete_selector": "punctuation.accessor"
```

This will ensure that the auto-complete will only trigger on "." in the source code.

Now, this is not a complete solution because the original triggers that this server enables are:
```
"."
":"
"<"
"""
"'"
"/"
"@"
"*"
" "
```

So you might want to tweak that `auto_complete_selector` setting to enable it in more cases but that requires a bit of work as `auto_complete_selector` works based on scopes and not just plain characters like the server does. That's actually a good thing because it's pretty dumb to trigger completion based on character, regardless of the scope, but that means it requires more work to set up for a specific syntax.

**Comment by rchl** [comment]
I might be OK with creating a complete solution for this that uses `auto_complete_selector` but I'm not so sure about disabling that space trigger because I would want the completion to trigger when typing values in an object literal, for example:

```
{
  foo: |  // <here
}
```

or after typing `await` in `await someFunction()`, for example.

**Comment by pelemarse** [comment]
Oh, that setting helped! Thank you very much!
But it would be amazing if this functionality could be expanded in the future.:)

**Comment by rwols** [comment]
> But it would be amazing if this functionality could be expanded in the future.:)

Expanded into what?

**Comment by pelemarse** [comment]
> Expanded into what?

That autocomplete only calls on `"." ":" "<" """ "'" "/" "@" "*"`

**Comment by rchl** [comment]
We only have setting to set triggers based on scope because the thinking here is that those are superior to character triggers.

That said, replicating space trigger with scopes could prove difficult or at least very verbose. I haven't tried but it could take some time to handle all cases.

Additionally, if we don't agree on whether completion should trigger or not in certain situations then we can't make a generic change that will satisfy everyone.

**Comment by rchl** [comment]
I don't think there is anything to act on here. Disabling space trigger in general might not be a change that people would like universally.

**Comment by predragnikolic** [comment]
There is a new Sublime text 4 setting in user preferences that disables showing autocomplete on space. That setting is `"auto_complete_when_likely"`. You can set it to `false`.

**Comment by goulashsoup** [comment]
1. Open native ST **Preferences: Settings**
2. Add `"auto_complete": false`.

For me this worked for `LSP-pyright`, I would expect it to behave equivalent for `LSP-vue`.
